services:
    # TWIG EXTENSION
    eschmar.twig.menu_extension:
        class: Eschmar\MenuBundle\Twig\MenuExtension
        tags:
            - { name: twig.extension }

    # HELPER
    eschmar.helper.menu_name_parser:
        class: Eschmar\MenuBundle\Helper\MenuNameParser
        arguments: [ "%kernel.bundles%" ]