services:
    # TWIG EXTENSION
    Eschmar\MenuBundle\Twig\MenuExtension:
        autowire: true
        class: Eschmar\MenuBundle\Twig\MenuExtension
        tags:
            - { name: twig.extension }

    # HELPER
    Eschmar\MenuBundle\Helper\MenuNameParser:
        class: Eschmar\MenuBundle\Helper\MenuNameParser
        arguments: [ "%kernel.bundles%" ]