services:
    # TWIG EXTENSION
    Eschmar\MenuBundle\Twig\MenuExtension:
        autowire: true
        class: Eschmar\MenuBundle\Twig\MenuExtension
        tags:
            - { name: twig.extension }
